In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\ASUS\\.vscode\\lib.pr.py\\data\\raw\\salesdata.csv")

In [3]:
df

,OrderID,CustomerName,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod
0,1,Amit Sharma,Delhi,Laptop,Electronics,55000,1,2024-01-05,Card
1,2,Rahul Verma,Mumbai,Phone,Electronics,20000,2,2024-01-06,Cash
2,3,Sneha Gupta,Pune,Headphones,Electronics,1500,3,2024-01-07,UPI
3,4,Ankit Jain,Delhi,Table,Furniture,7000,1,2024-01-08,Card
4,5,Neha Singh,Bangalore,Chair,Furniture,3000,2,2024-01-09,UPI
5,6,Rohit Kumar,Chennai,TV,Electronics,40000,1,2024-01-10,Cash
6,7,Pooja Mehta,Delhi,Sofa,Furniture,25000,1,2024-01-11,Card
7,8,Karan Patel,Ahmedabad,Phone,Electronics,18000,1,2024-01-12,UPI
8,9,Simran Kaur,Amritsar,Laptop,Electronics,60000,1,2024-01-13,Card
9,10,Vikas Yadav,Noida,Table,Furniture,6500,2,2024-01-14,Cash
10,11,Aman Singh,Delhi,Chair,Furniture,3200,1,2024-01-15,UPI
11,12,Ritu Kapoor,Mumbai,TV,Electronics,42000,1,2024-01-16,Card
12,13,Deepak Sharma,Pune,Phone,Electronics,22000,1,2024-01-17,Cash
13,14,Meena Joshi,Jaipur,Sofa,Furniture,27000,1,2024-01-18,UPI
14,15,Sahil Khan,Delhi,Headphones,Electronics,2000,2,2024-01-19,Card
15,16,Arjun Das,Kolkata,Laptop,Electronics,53000,1,2024-01-20,UPI
16,17,Anjali Roy,Kolkata,Chair,Furniture,3500,2,2024-01-21,Cash
17,18,Mohit Bansal,Delhi,Table,Furniture,7200,1,2024-01-22,Card
18,19,Nisha Arora,Chandigarh,Phone,Electronics,21000,2,2024-01-23,UPI
19,20,Harsh Gupta,Delhi,TV,Electronics,39000,1,2024-01-24,Cash

In [4]:
df["OrderDate"]=pd.to_datetime(df["OrderDate"])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        20 non-null     int64
 1   CustomerName   20 non-null     object
 2   City           20 non-null     object
 3   Product        20 non-null     object
 4   Category       20 non-null     object
 5   Price          20 non-null     int64
 6   Quantity       20 non-null     int64
 7   OrderDate      20 non-null     datetime64[ns]
 8   PaymentMethod  20 non-null     object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 1.5+ KB

In [6]:
df.head(5)

,OrderID,CustomerName,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod
0,1,Amit Sharma,Delhi,Laptop,Electronics,55000,1,2024-01-05,Card
1,2,Rahul Verma,Mumbai,Phone,Electronics,20000,2,2024-01-06,Cash
2,3,Sneha Gupta,Pune,Headphones,Electronics,1500,3,2024-01-07,UPI
3,4,Ankit Jain,Delhi,Table,Furniture,7000,1,2024-01-08,Card
4,5,Neha Singh,Bangalore,Chair,Furniture,3000,2,2024-01-09,UPI

In [7]:
df.columns

Index(['OrderID', 'CustomerName', 'City', 'Product', 'Category', 'Price',
       'Quantity', 'OrderDate', 'PaymentMethod'],
      dtype='object')

In [8]:
df.dtypes

OrderID                   int64
CustomerName             object
City                     object
Product                  object
Category                 object
Price                     int64
Quantity                  int64
OrderDate        datetime64[ns]
PaymentMethod            object
dtype: object

In [9]:
df.describe()

        OrderID         Price   Quantity            OrderDate
count  20.00000     20.000000  20.000000                   20
mean   10.50000  22795.000000   1.400000  2024-01-14 12:00:00
min     1.00000   1500.000000   1.000000  2024-01-05 00:00:00
25%     5.75000   5750.000000   1.000000  2024-01-09 18:00:00
50%    10.50000  20500.000000   1.000000  2024-01-14 12:00:00
75%    15.25000  39250.000000   2.000000  2024-01-19 06:00:00
max    20.00000  60000.000000   3.000000  2024-01-24 00:00:00
std     5.91608  19345.323792   0.598243                  NaN

In [10]:
df.rename(columns={"OrderDate":"order_date"},inplace=True)
df.rename(columns={"CustomerName":"customer_name"},inplace=True)

In [11]:
df["Price"]=df["Price"].astype(float)

In [12]:
df["Quantity"]=df["Quantity"].astype(int)

In [13]:
df["total_amount"]=df["Price"]*df["Quantity"]

KPI analysis

In [14]:
Total_revenue=df["total_amount"].sum()
print(Total_revenue)

514900.0

In [15]:
avrage_order_value=df.groupby("OrderID")["total_amount"].sum().mean()
print(avrage_order_value,"avrage_order_value")

25745.0 avrage_order_value

In [16]:
hsp=df.groupby("Product")["Quantity"].sum().sort_values(ascending=False).head(1)
print(hsp)

Product
Phone    6
Name: Quantity, dtype: int64

In [17]:
mcc=df.groupby("City")["Quantity"].count().sort_values(ascending=False).head(1)
print(mcc)

City
Delhi    7
Name: Quantity, dtype: int64

In [42]:
df.groupby("Product")["Price"].max().sort_values(ascending=False)

Product
Laptop        60000.0
TV            42000.0
Sofa          27000.0
Phone         22000.0
Table          7200.0
Chair          3500.0
Headphones     2000.0
Name: Price, dtype: float64

In [44]:
df["Category"].value_counts()

Category
Electronics    12
Furniture       8
Name: count, dtype: int64